---
- name: Building harbor docker images
  hosts: all
  become: true
  vars_files:
    - "group_vars/defaults.yml"
  roles:
    - role: docker-harbor
      harbor:
        domain: harbor.devapp.shop
        username: admin
        password: admin
        project: goharbor
        upload: false
