---
- name: upgrade the package sudo
  become_method: sudo
  shell: apt-get --only-upgrade install sudo

- name: upgrade the package sudo
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
