---
- name: add postgresql apt key.
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  register: add_repository_key

- name: add postgresql sources for ubuntu 18.04
  apt_repository: repo='deb https://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main' state=present
  when: ansible_distribution_version == "18.04"

- name: install postgresql-client 12
  apt:
    update_cache: yes
    state: present
    name:
      - postgresql-client-12
  when: version == 12
