---
- name: copy files to temporary directory
  copy:
    src: "1.19/alpine/"
    dest: "/tmp/dockerfile/"

- name: build docker image
  shell: |
    chdir /tmp/dockerfile
    chmod 0755 /tmp/dockerfile/*.sh
    docker build -t '{{ image.name }}:{{ image.tag }}' .

- name: tagging docker image
  shell: |
    chdir /tmp/dockerfile
    docker tag '{{ image.name }}:{{ image.tag }}' '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'

- name: push docker image
  shell: |
    chdir /tmp/dockerfile/
    cat /tmp/dockerfile/.harbor.credentials | docker login 'https://{{ harbor.domain }}' --username {{ harbor.username }} --password-stdin
    docker push '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'
  when: harbor.upload == true or harbor.upload == "true"
