---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-cm
  namespace: default
data:
  GITLAB_OMNIBUS_CONFIG: |
    # Public name and SSL offloading
    external_url '<YOUR_GITLAB_PUBLIC_HOST>'

    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    nginx['listen_addresses'] = ["0.0.0.0", "[::]"]

    # Misc
    gitlab_rails['time_zone'] = 'Asia/Seoul'
    root_pass = 'admin123$'
    gitlab_rails['initial_root_password'] = root_pass unless root_pass.to_s == ''
    runner_token = 'AppleBananaMelonJnEFdPIC'
    gitlab_rails['initial_shared_runners_registration_token'] = runner_token unless runner_token.to_s == ''
    gitlab_rails['lfs_enabled'] = true
    gitlab_rails['gitlab_shell_ssh_port'] = 22
    gitlab_rails['usage_ping_enabled'] = false

    # External postgresql
    postgresql['enable'] = false
    gitlab_rails['auto_migrate'] = true
    gitlab_rails['db_username'] = 'gitlab'
    gitlab_rails['db_password'] = 'admin123$'
    gitlab_rails['db_database'] = 'gitlab'
    gitlab_rails['db_host'] = 'postgres-service'
    gitlab_rails['db_port'] = 5432
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'utf8'

    # Monitoring & Dashboard
    prometheus['enable'] = false
    grafana['enable'] = false
