---
- name: 'install chrony'
  package:
    name: 'chrony'
    state: 'present'

- name: 'register chrony service'
  service:
    name: 'chrony'
    enabled: 'yes'
    state: 'started'

- name: 'configure chrony'
  template:
    src: 'chrony.conf.j2'
    dest: '/etc/chrony/chrony.conf'
  notify: 'restart chrony on ubuntu'

