---
- name: install the package for strong password checking
  apt:
    name: libpam-pwquality
    state: 'present'
    update_cache: 'yes'

- name: configure password complecity policy
  template:
    src: 'pwquality.conf.j2'
    dest: '/etc/security/pwquality.conf'
    mode: 0644
    owner: root
    group: root

- name: protect login as root
  shell:
    cmd: |
      gpasswd -a root wheel
      chgrp wheel /bin/su
      chmod 4750 /bin/su
  become: true
  ignore_errors: true

- name: configure protect login as root
  lineinfile:
    dest: '/etc/pam.d/su'
    line: "{{ item }}"
    insertafter: EOF
  with_items:
    - "auth       required   pam_wheel.so use_uid"
