---
- name: generate kafka dockerfile
  vars:
    kafka_version: "{{ kafka.version }}"
    kafka_home: "{{ kafka.homedir }}"
    scala_version: "{{ kafka.scala_version }}"
  template:
    src: 'Dockerfile.j2'
    dest: '/tmp/dockerfile/Dockerfile'
    mode: 0755

- name: copy files to temporary directory
  copy:
    src: "ubuntu/entrypoint.sh"
    dest: "/tmp/dockerfile/"

- name: build docker image
  shell: |
    chdir /tmp/dockerfile/
    docker build -t "{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}" .

- name: push docker image
  shell: |
    chdir /tmp/dockerfile/
    cat /tmp/dockerfile/.harbor.credentials | docker login 'https://{{ harbor.domain }}' --username {{ harbor.username }} --password-stdin
    docker push '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'
  when: harbor.upload == true or harbor.upload == "true"

- name: flush temporary working directory
  file:
    path: '/tmp/dockerfile/'
    state: absent
  ignore_errors: true
