---
- name: apt-get update
  apt: update_cache=yes cache_valid_time=86400

- name: apt install software-properties-common
  apt: name=software-properties-common state=latest cache_valid_time=3600

- name: apt-add-repository
  shell: apt-add-repository --yes --update ppa:ansible/ansible

- name: apt install ansible
  apt: name=ansible state=latest cache_valid_time=3600
