---
- name: upgrade the package for kubernetes
  apt:
    pkg:
      - ca-certificates
      - auditd
      - parted
      - lsb-release
    state: latest

- name: register auditd service
  service:
    name: 'auditd'
    enabled: 'yes'
    state: 'started'

- include_tasks: ubuntu-boilerplate.yml
  tags: configure boilerplate

- include_tasks: ubuntu-disk-partition.yml
  when: disk_part == true or disk_part == "true"
  tags: disk partition

- include_tasks: ubuntu-docker.yml
  tags: install docker

- include_tasks: ubuntu-iptables.yml
  tags: configure iptables

- include_tasks: ubuntu-logrotate.yml
  tags: configure logrotate

- include_tasks: ubuntu-kubelet.yml
  tags: install kubelet

- include_tasks: ubuntu-cni.yml
  tags: install cni plugin

- include_tasks: ubuntu-bootstrap.yml
  tags: install bootstrap

- include_tasks: "ubuntu-nameserver.yml"
  tags: configuration nameserver

- name: relabel the operating system now that all bits are installed.
  shell: "touch /.autorelabel"

#- include_tasks: ubuntu-reboot.yml
#  tags: reboot