---
# prepared eks custom amis
# https://github.com/aws-samples/amazon-eks-custom-amis/blob/main/scripts/ubuntu1804/boilerplate.sh
- name: copy functions file for provisioning eks node
  copy:
    src: 'functions.sh'
    dest: '/tmp/'
    mode: 0755

- name: wait for cloudinit
  shell: |
    . /tmp/functions.sh
    wait_for_cloudinit

- name: check exists jq executable file
  stat:
    path: '/usr/bin/jq'
  register: jq_shell_file

- name: install the package jq
  get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    dest: /usr/bin/jq
    mode: 0755
    force_basic_auth: yes
  when: not jq_shell_file.stat.exists

- name: add environment vars for http proxy
  lineinfile:
    path: '/etc/environment'
    regexp: '^{{ item.key }}\ ?='
    line: "{{ item.key }}=\"{{ item.value }}\""
  with_dict: "{{ environment_vars }}"
