---
# https://github.com/aws-samples/amazon-eks-custom-amis/blob/main/scripts/ubuntu1804/cleanup.sh
- name: apt - remove packages from the cache
  apt: autoclean=yes

- name: apt - remove dependencies that are no longer required
  apt: autoremove=yes

- name: clean up files to reduce confusion
  shell: |
    rm -rf /var-old
    rm -rf /var/log-old
    rm -rf /var/log/audit-old
    rm -rf /home-old
    rm -rf /etc/packer
    rm -rf /var/lib/docker-old
    touch /etc/machine-id
