---
- name: reboot host
  shell: sleep 2 && shutdown -r now "Applied disk partition"
  async: 1
  poll: 0
  ignore_errors: yes

- name: wait for host
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 10
    timeout: 300
  when: reboot_wait|bool

- name: Interval before next task
  pause:
    seconds: 0
  when: reboot_interval|bool

- name: check rebooted os
  debug:
    msg: "RE-BOOTED OS"
