---
- name: sonarqube docker image pull
  shell: |
    docker pull {{ image.name }}:{{ image.tag }}

- name: tagging docker image
  shell: |
    docker tag '{{ image.name }}:{{ image.tag }}' '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'

- name: push docker image
  shell: |
    chdir /tmp/dockerfile/
    cat /tmp/dockerfile/.harbor.credentials | docker login 'https://{{ harbor.domain }}' --username {{ harbor.username }} --password-stdin
    docker push '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'
  when: harbor.upload == true or harbor.upload == "true"

- name: flush temporary working directory
  file:
    path: '/tmp/dockerfile/'
    state: absent
  ignore_errors: true

- name: configure vm.max_map_count for sysctl.conf
  sysctl:
    name: vm.max_map_count
    value: 524288
    sysctl_set: yes
    state: present
    reload: true

- name: configure fs.file.max for sysctl.conf
  sysctl:
    name: fs.file-max
    value: 131072
    sysctl_set: yes
    state: present
    reload: true
