---
- name: Building kiali docker images
  hosts: all
  become: true
  vars_files:
    - "group_vars/defaults.yml"
  roles:
    - role: docker-kiali
      harbor:
        domain: harbor.devapp.shop
        username: admin
        password: admin!234
        project: kiali
        upload: false
