---
- name: assert variables
  assert:
    that: "{{ item }} is defined"
    msg: "{{ item  }} is not defined"
  with_items:
    - harbor.domain
    - harbor.username
    - harbor.password
    - harbor.project
    - harbor.upload
    - image.name
    - image.tag

- name: pre-processor for building docker image
  shell: |
    mkdir -p /tmp/dockerfile
    echo "{{ harbor.password }}" > /tmp/dockerfile/.harbor.credentials

- name: include os-specific vars
  include_vars: "{{ os_name }}.yml"

- name: include os specific task
  include_tasks: "{{ os_name }}.yml"

