---
- name: Building Kubernetes Nginx Worker Node AMI
  hosts: all
  become: true
  vars_files:
    - "group_vars/defaults.yml"
  roles:
    - role: aws-eks
    - role: docker-eksnode-build
      harbor:
        domain: harbor.devapp.shop
        username: admin
        password: admin
        project: tools
      docker_image: "dxnginx-1.19:1.0"
