---
- name: include os-specific vars
  include_vars: "{{ os_name }}.yml"

- name: prepare install task for packer.
  shell: |
    rm -f /usr/bin/packer
    rm -f /opt/packer/bin/packer
    rm -f /tmp/packer*.zip

- name: include os specific task
  include_tasks: "{{ os_name }}.yml"

