---
#- name: ntpq syc 단일 서버에서는 불필요 , 확장서버에서만 사용
#  become_method: sudo
#  shell: |
#    ntpq -p

#- name: copy whatap zip file to remote server
#  copy:
#    src: /Users/jaehyun.yang/workspace/packer/whatap
#    mode: 755

- name: environment add java path
  shell: |
    echo "JAVA_HOME={{ JAVA_8_HOME_PATH }}" >> /etc/environment

- name: Download whatap server agent file
  get_url:
    #url: https://apm-public.s3.ap-northeast-2.amazonaws.com/temp/presales/whatap_server/whatap_single-2.1.0.3753_patch.tar.gz
    url: https://apm-public.s3.ap-northeast-2.amazonaws.com/temp/presales/whatap_server/whatap_single-2.1.5.3932_stable_bespin.tar.gz
    dest: /tmp/
    force_basic_auth: yes

- name: Unarchive whatap file that is already on the remote machine
  unarchive:
    #src: /tmp/whatap_single-2.1.0.3753_patch.tar.gz
    src: /tmp/whatap_single-2.1.5.3932_stable_bespin.tar.gz
    dest: "{{ whatap_server_home_path }}"
    remote_src: yes
    mode: 0755

- name: Whatap bin env setting
  shell: |
    sed -i "s|#JAVA_HOME=|JAVA_HOME={{ JAVA_8_HOME_PATH }}|g" {{ whatap_path }}/bin/front.sh

- name: Whatap bin env setting
  shell: |
    sed -i "s|#JAVA_HOME=|JAVA_HOME={{ JAVA_8_HOME_PATH }}|g" {{ whatap_path }}/bin/account.sh

- name: Whatap account config
  shell: |
    cd {{ whatap_path }}/conf
    sed -i "s|owner={ip address can be showed by ifconfig/ipconfig}|owner=127.0.0.1|g" account.conf
    sed -i "s|license={server license}|license={{ whatap_license }}|g" account.conf

- name: Whatap front config
  shell: |
    cd {{ whatap_path }}/conf
    sed -i "s|region.proxy.address={IP_ADDRESS_accessable_from_AGENT}|region.proxy.address=127.0.0.1|g" front.conf
    echo "\n\n#whatap rest api tokenkey\ninternal_api_key={{whatap_restapi_token_key}}" >>  front.conf

- name: "create whatap-single service"
  template:
    src: "whatap-single.service.j2"
    dest: "/etc/systemd/system/whatap-single.service"
    mode: 0664
  notify:
    - restart whatap