---
- name: create whatap home dir
  file:
    path: '{{ whatap_server_home_path }}'
    state: directory

- include_tasks: ubuntu-sysconf.yml
  tags: configure sysconf

- include_tasks: ubuntu-security.yml
  tags: configure security

- include_tasks: ubuntu-single-whatap.yml
  tags: whatap single install
  when: whatap_server_type == "single"

- include_tasks: ubuntu-multi-whatap.yml
  tags: whatap multi install
  when: whatap_server_type == "multi" 