---
# defaults file for docker-kafka
# mandatory variables for harbor
harbor:
  domain: harbor.toolchain
  username: admin
  password: admin123$
  project: tools
  upload: false

# mandatory variables for docker image
image:
  name: kafka-kraft
  tag: "{{ kafka.version }}"

java_base_image: "adoptopenjdk/openjdk11:jdk-11.0.12_7-ubuntu-slim"

kafka:
  version: 3.0.0
  homedir: /opt/kafka
  scala_version: 2.13

download_url: "https://archive.apache.org/dist/kafka/{{ kafka.version }}/kafka_{{ kafka.scala_version }}-{{ kafka.version }}.tgz"
download_target: "/tmp/kafka-{{ kafka.scala_version }}-{{ kafka.version }}.tar.gz"
