---
- name: harbor docker images pull
  shell: |
    docker pull goharbor/chartmuseum-photon:{{ image.tag }}
    docker pull goharbor/harbor-core:{{ image.tag }}
    docker pull goharbor/harbor-jobservice:{{ image.tag }}
    docker pull goharbor/notary-server-photon:{{ image.tag }}
    docker pull goharbor/notary-signer-photon:{{ image.tag }}
    docker pull goharbor/harbor-portal:{{ image.tag }}
    docker pull goharbor/registry-photon:{{ image.tag }}
    docker pull goharbor/harbor-registryctl:{{ image.tag }}
    docker pull goharbor/harbor-db:{{ image.tag }}
    docker pull goharbor/redis-photon:{{ image.tag }}
    docker pull goharbor/trivy-adapter-photon:{{ image.tag }}
    docker pull goharbor/harbor-exporter:{{ image.tag }}

- name: tagging docker images
  shell: |
    docker tag goharbor/chartmuseum-photon:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/chartmuseum-photon:{{ image.tag }}
    docker tag goharbor/harbor-core:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/harbor-core:{{ image.tag }}
    docker tag goharbor/harbor-jobservice:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/harbor-jobservice:{{ image.tag }}
    docker tag goharbor/notary-server-photon:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/notary-server-photon:{{ image.tag }}
    docker tag goharbor/notary-signer-photon:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/notary-signer-photon:{{ image.tag }}
    docker tag goharbor/harbor-portal:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/harbor-portal:{{ image.tag }}
    docker tag goharbor/registry-photon:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/registry-photon:{{ image.tag }}
    docker tag goharbor/harbor-registryctl:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/harbor-registryctl:{{ image.tag }}
    docker tag goharbor/harbor-db:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/harbor-db:{{ image.tag }}
    docker tag goharbor/redis-photon:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/redis-photon:{{ image.tag }}
    docker tag goharbor/trivy-adapter-photon:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/trivy-adapter-photon:{{ image.tag }}
    docker tag goharbor/harbor-exporter:{{ image.tag }} {{ harbor.domain }}/{{harbor.project}}/harbor-exporter:{{ image.tag }}

- name: push docker images
  shell: |
    chdir /tmp/dockerfile
    cat /tmp/dockerfile/.harbor.credentials | docker login 'https://{{ harbor.domain }}' --username {{ harbor.username }} --password-stdin
    docker push {{ harbor.domain }}/{{harbor.project}}/chartmuseum-photon:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/harbor-core:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/harbor-jobservice:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/notary-server-photon:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/notary-signer-photon:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/harbor-portal:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/registry-photon:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/harbor-registryctl:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/harbor-db:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/redis-photon:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/trivy-adapter-photon:{{ image.tag }}
    docker push {{ harbor.domain }}/{{harbor.project}}/harbor-exporter:{{ image.tag }}
  when: harbor.upload == true or harbor.upload == "true"

- name: flush temporary working directory
  file:
    path: '/tmp/dockerfile/'
    state: absent
  ignore_errors: true
