---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - name: postgresdb
      protocol: TCP
      port: 5432
      targetPort: 5432
