image: gitlab/gitlab-runner:v13.0.0

# Update the security context values to the user ID in the ubuntu image
securityContext:
  fsGroup: 999
  runAsUser: 999

rbac:
  create: false
  serviceAccountName: gitlab-runner-admin

runners:
  secret: gitlab-runner-secret
  token: "<YOUR_RUNNERS_TOKEN>"
  config: |
    [[runners]]
      token="<YOUR_RUNNERS_TOKEN>"
      executor = "docker"
      [runners.docker]
        tls_verify = false
        image = "alpine:3.4"
        privileged = true
        disable_cache = false
        volumes = ["/cache"]
      [runners.kubernetes]
        image = "ubuntu:18.04"
        privileged = true
        [runners.cache]
          Type = "s3"
          #Path = "runner"
          Shared = true
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - harbor
