---
- name: copy files to temporary directory
  copy:
    src: "11/jdk/alpine/"
    dest: "/tmp/dockerfile"

- name: build docker image
  shell: |
    cd /tmp/dockerfile/
    chmod 0755 /tmp/dockerfile/slim-java.sh
    docker build -t "{{ image.name }}:{{ image.tag }}" -f /tmp/dockerfile/Dockerfile.hotspot.releases.slim .

- name: tagging docker image
  shell: |
    chdir /tmp/dockerfile/
    docker tag '{{ image.name }}:{{ image.tag }}' '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'

- name: push docker image
  shell: |
    chdir /tmp/dockerfile/
    cat /tmp/dockerfile/.harbor.credentials | docker login 'https://{{ harbor.domain }}' --username {{ harbor.username }} --password-stdin
    docker push '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'
  when: harbor.upload == true or harbor.upload == "true"
