---
- name: read disk info of /dev/nvme1n1
  parted:
    device: /dev/nvme1n1
    unit: GB
  register: before_part

- name: print disk info of /dev/nvme1n1
  debug:
    msg: "{{ before_part }}"

- name: primary partition number 1 on /dev/sdb is created
  parted:
    device: /dev/nvme1n1
    label: gpt
    number: 1
    name: docker
    part_start: 0%
    part_end: 20GB
    state: present

- name: primary partition number 2 on /dev/sdb is created
  parted:
    device: /dev/nvme1n1
    label: gpt
    number: 2
    name: data
    part_start: 20GB
    part_end: 100%
    state: present

- name: format nvme1n1p1
  filesystem:
    dev: /dev/nvme1n1p1
    fstype: ext4

- name: format nvme1n1p2
  filesystem:
    dev: /dev/nvme1n1p2
    fstype: ext4

- name: mount filesystem for '/var/lib/docker'
  mount:
    src: /dev/nvme1n1p1
    path: /var/lib/docker
    fstype: ext4
    opts: auto,nodev
    state: present
    fstab: /etc/fstab

- name: mount filesystem for '/data'
  mount:
    src: /dev/nvme1n1p2
    path: /data
    fstype: ext4
    opts: auto,nodev
    state: present
    fstab: /etc/fstab
