---
kind: Service
apiVersion: v1
metadata:
  labels:
    toolchain: nexus
  name: nexus-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    toolchain: nexus