---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    toolchain: nexus
  name: nexus
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      toolchain: nexus
  template:
    metadata:
      labels:
        toolchain: nexus
    spec:
      securityContext:
        fsGroup: 200
        runAsUser: 200
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: nexus
          image: sonatype/nexus3:3.31.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: ENABLE_ANONYMOUS_ACCESS
              value: "false"
            - name: NEXUS_SECURITY_RANDOMPASSWORD
              value: "false"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8081
            initialDelaySeconds: 50
            periodSeconds: 5
            failureThreshold: 10
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pv