---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: default
  labels:
    name: nexus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/nexus-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: nexus-pv
