apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: default
  labels:
    app: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command: ["/bin/sh","-c","sysctl -w vm.max_map_count=524288; sysctl -w fs.file-max=131072; ulimit -n 524288; ulimit -u 8192"]
          securityContext:
            privileged: true
            # runAsUser: 0
      containers:
        - name: sonarqube
          image: sonarqube:8.9.0-community
          imagePullPolicy: IfNotPresent
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              value: "sonarqube123$"
            - name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://postgres-service:5432/sonarqube"
            - name: SONARQUBE_JDBC_USERNAME
              value: "sonarqube"
          ports:
            - containerPort: 9000
