---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: sonarqube-service
  labels:
    app: sonarqube
spec:
  selector:
    app: sonarqube
  type: ClusterIP
  ports:
    - name: sonarqube
      protocol: TCP
      port: 9000
      targetPort: 9000

