apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: testweb-virtualservice
  namespace: default
spec:
  gateways:
  - testweb-gateway
  hosts:
  - testweb.azjaehyun.shop
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: testweb-service
        port:
          number: 8080