---
- name: apt-get update
  apt: update_cache=yes cache_valid_time=86400

- include_tasks: ubuntu-docker.yml
  tags: install docker

- include_tasks: ubuntu-nameserver.yml
  tags: configuration nameserver
  when: 1 == 2
