---
- name: ensure IPv6 is disabled
  lineinfile:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable=1)\"[^\"]*)(\".*)'
    line: '\1ipv6.disable=1 \2'
    backrefs: yes
    state: present
  notify: update grub
  when: ipv6 == "disabled"