---
- name: gitlab-runner docker image pull
  shell: |
    docker pull gitlab/{{ image.name }}:{{ image.tag }}.0

- name: tagging docker image
  shell: |
    docker tag 'gitlab/{{ image.name }}:{{ image.tag }}.0' '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'

- name: push docker image
  shell: |
    chdir /tmp/dockerfile/
    cat /tmp/dockerfile/.harbor.credentials | docker login 'https://{{ harbor.domain }}' --username {{ harbor.username }} --password-stdin
    docker push '{{ harbor.domain }}/{{harbor.project}}/{{ image.name }}:{{ image.tag }}'
  when: harbor.upload == true or harbor.upload == "true"

- name: flush temporary working directory
  file:
    path: '/tmp/dockerfile/'
    state: absent
  ignore_errors: true
