---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume-3
  namespace: default
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-3
  persistentVolumeReclaimPolicy: Recycle

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busybox-claim
  namespace: default
  labels:
    app: busybox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
