---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    toolchain: grafana
  name: grafana
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      toolchain: grafana
  template:
    metadata:
      labels:
        toolchain: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:8.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-pvolume
              mountPath: /data/grafana/
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: false
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources