  "grafana-cm.yaml" 17L, 395C                                                                                                                                               17,9          All
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: grafana-datasources
    namespace: default
    labels:
      grafana_datasource: "1"
  data:
    datasource.yaml: |-
      apiVersion: 1
      datasources:
      - name: CloudWatch
        type: cloudwatch
        jsonData:
          authType: default
          defaultRegion: ap-northeast-2
          assumeRoleArn: <YOUR_AWS_IAM_ROLE_FOR_GRAFANA>
