---
- include_tasks: ubuntu-1.7.yml
  when: image.tag == 1.7 or image.tag == "1.7"
  tags: install fluent-bit 1.7

- name: flush temporary working directory
  file:
    path: '/tmp/dockerfile/'
    state: absent
  ignore_errors: true
