---
- name: Building AWS Bastion AMI Image
  hosts: all
  become: true
  vars_files:
    - "group_vars/defaults.yml"
  roles:
    - role: bastion
    - role: whatap
      whatap_server_type: "single"
    - role: cleansing